/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { CancelButtonProps } from "./CancelButton";
import { DeleteWhiteButtonProps } from "./DeleteWhiteButton";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type DeleteItemVeriPopupOverridesProps = {
    DeleteItemVeriPopup?: PrimitiveOverrideProps<ViewProps>;
    "Frame 201"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 183"?: PrimitiveOverrideProps<FlexProps>;
    "Do you want to delete this item?"?: PrimitiveOverrideProps<TextProps>;
    Text?: PrimitiveOverrideProps<TextProps>;
    "Bad gateway"?: PrimitiveOverrideProps<ViewProps>;
    Group43512416?: PrimitiveOverrideProps<ViewProps>;
    Group43512417?: PrimitiveOverrideProps<ViewProps>;
    Vector43512418?: PrimitiveOverrideProps<IconProps>;
    Vector43512419?: PrimitiveOverrideProps<IconProps>;
    Group43512420?: PrimitiveOverrideProps<ViewProps>;
    Vector43512421?: PrimitiveOverrideProps<IconProps>;
    Vector43512422?: PrimitiveOverrideProps<IconProps>;
    Group43512423?: PrimitiveOverrideProps<ViewProps>;
    Vector43512424?: PrimitiveOverrideProps<IconProps>;
    Vector43512425?: PrimitiveOverrideProps<IconProps>;
    Group43512426?: PrimitiveOverrideProps<ViewProps>;
    Vector43512427?: PrimitiveOverrideProps<IconProps>;
    Vector43512428?: PrimitiveOverrideProps<IconProps>;
    Group43512429?: PrimitiveOverrideProps<ViewProps>;
    Group43512430?: PrimitiveOverrideProps<ViewProps>;
    Group43512431?: PrimitiveOverrideProps<ViewProps>;
    Vector43512432?: PrimitiveOverrideProps<IconProps>;
    Group43512433?: PrimitiveOverrideProps<ViewProps>;
    Vector43512434?: PrimitiveOverrideProps<IconProps>;
    Group43512435?: PrimitiveOverrideProps<ViewProps>;
    Vector43512436?: PrimitiveOverrideProps<IconProps>;
    Group43512437?: PrimitiveOverrideProps<ViewProps>;
    Vector43512438?: PrimitiveOverrideProps<IconProps>;
    Vector43512439?: PrimitiveOverrideProps<IconProps>;
    Vector43512440?: PrimitiveOverrideProps<IconProps>;
    Group43512441?: PrimitiveOverrideProps<ViewProps>;
    Group43512442?: PrimitiveOverrideProps<ViewProps>;
    Vector43512443?: PrimitiveOverrideProps<IconProps>;
    sk?: PrimitiveOverrideProps<IconProps>;
    sh?: PrimitiveOverrideProps<IconProps>;
    Vector43512446?: PrimitiveOverrideProps<IconProps>;
    Vector43512447?: PrimitiveOverrideProps<IconProps>;
    Vector43512448?: PrimitiveOverrideProps<IconProps>;
    Vector43512449?: PrimitiveOverrideProps<IconProps>;
    Vector43512450?: PrimitiveOverrideProps<IconProps>;
    Vector43512451?: PrimitiveOverrideProps<IconProps>;
    Vector43512452?: PrimitiveOverrideProps<IconProps>;
    Vector43512453?: PrimitiveOverrideProps<IconProps>;
    Vector43512454?: PrimitiveOverrideProps<IconProps>;
    Vector43512455?: PrimitiveOverrideProps<IconProps>;
    Vector43512456?: PrimitiveOverrideProps<IconProps>;
    Vector43512457?: PrimitiveOverrideProps<IconProps>;
    Vector43512458?: PrimitiveOverrideProps<IconProps>;
    Vector43512459?: PrimitiveOverrideProps<IconProps>;
    Group43512460?: PrimitiveOverrideProps<ViewProps>;
    Vector43512461?: PrimitiveOverrideProps<IconProps>;
    Group43512462?: PrimitiveOverrideProps<ViewProps>;
    Vector43512463?: PrimitiveOverrideProps<IconProps>;
    Group43512464?: PrimitiveOverrideProps<ViewProps>;
    Vector43512465?: PrimitiveOverrideProps<IconProps>;
    Group43512466?: PrimitiveOverrideProps<ViewProps>;
    Vector43512467?: PrimitiveOverrideProps<IconProps>;
    Vector43512468?: PrimitiveOverrideProps<IconProps>;
    Vector43512469?: PrimitiveOverrideProps<IconProps>;
    Vector43512470?: PrimitiveOverrideProps<IconProps>;
    Group43512471?: PrimitiveOverrideProps<ViewProps>;
    Group43512472?: PrimitiveOverrideProps<ViewProps>;
    Group43512473?: PrimitiveOverrideProps<ViewProps>;
    Vector43512474?: PrimitiveOverrideProps<IconProps>;
    Vector43512475?: PrimitiveOverrideProps<IconProps>;
    Vector43512476?: PrimitiveOverrideProps<IconProps>;
    Group43512477?: PrimitiveOverrideProps<ViewProps>;
    Vector43512478?: PrimitiveOverrideProps<IconProps>;
    Group43512479?: PrimitiveOverrideProps<ViewProps>;
    Vector43512480?: PrimitiveOverrideProps<IconProps>;
    Vector43512481?: PrimitiveOverrideProps<IconProps>;
    "Frame 181"?: PrimitiveOverrideProps<FlexProps>;
    "Cancel Button"?: CancelButtonProps;
    "Line 75"?: PrimitiveOverrideProps<IconProps>;
    "Delete White Button"?: DeleteWhiteButtonProps;
} & EscapeHatchProps;
export declare type DeleteItemVeriPopupProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: DeleteItemVeriPopupOverridesProps | undefined | null;
}>;
export default function DeleteItemVeriPopup(props: DeleteItemVeriPopupProps): React.ReactElement;
