/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { SearchbarmainProps } from "./Searchbarmain";
import { TagsbuttonProps } from "./Tagsbutton";
import { AddButtonProps } from "./AddButton";
import { LogoyellowProps } from "./Logoyellow";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type FooterOverridesProps = {
    Footer?: PrimitiveOverrideProps<FlexProps>;
    "Bottom Primary Frame"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 50"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 47"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 45"?: PrimitiveOverrideProps<FlexProps>;
    "Search your favorite prompts!"?: PrimitiveOverrideProps<TextProps>;
    "Frame 44"?: PrimitiveOverrideProps<FlexProps>;
    "search bar (main)"?: SearchbarmainProps;
    "Frame 21"?: PrimitiveOverrideProps<FlexProps>;
    "tags button2582383"?: TagsbuttonProps;
    "tags button2582384"?: TagsbuttonProps;
    "tags button2582385"?: TagsbuttonProps;
    "tags button2582386"?: TagsbuttonProps;
    "Add Button"?: AddButtonProps;
    "Frame 46"?: PrimitiveOverrideProps<FlexProps>;
    "About is"?: PrimitiveOverrideProps<FlexProps>;
    "About Us"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582391"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582392"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582393"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582394"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582395"?: PrimitiveOverrideProps<TextProps>;
    Help2582396?: PrimitiveOverrideProps<FlexProps>;
    Help2582397?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582398"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582399"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582400"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582401"?: PrimitiveOverrideProps<TextProps>;
    "Shop prompt"?: PrimitiveOverrideProps<FlexProps>;
    "Shop Prompts"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582404"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582405"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582406"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582407"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582408"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582409"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582410"?: PrimitiveOverrideProps<TextProps>;
    Services?: PrimitiveOverrideProps<FlexProps>;
    "Account & Services"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582413"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582414"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582415"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582416"?: PrimitiveOverrideProps<TextProps>;
    "Text with links here2582417"?: PrimitiveOverrideProps<TextProps>;
    "Frame 48"?: PrimitiveOverrideProps<FlexProps>;
    "logo-yellow"?: LogoyellowProps;
    "Get Best Prompts with Parazon."?: PrimitiveOverrideProps<TextProps>;
    "Online test"?: PrimitiveOverrideProps<ViewProps>;
    Vector2582422?: PrimitiveOverrideProps<IconProps>;
    Group2582423?: PrimitiveOverrideProps<ViewProps>;
    Group2582424?: PrimitiveOverrideProps<ViewProps>;
    Vector2582425?: PrimitiveOverrideProps<IconProps>;
    Vector2582426?: PrimitiveOverrideProps<IconProps>;
    Vector2582427?: PrimitiveOverrideProps<IconProps>;
    Group2582428?: PrimitiveOverrideProps<ViewProps>;
    Vector2582429?: PrimitiveOverrideProps<IconProps>;
    Vector2582430?: PrimitiveOverrideProps<IconProps>;
    Group2582431?: PrimitiveOverrideProps<ViewProps>;
    Vector2582432?: PrimitiveOverrideProps<IconProps>;
    Group2582433?: PrimitiveOverrideProps<ViewProps>;
    Vector2582434?: PrimitiveOverrideProps<IconProps>;
    Vector2582435?: PrimitiveOverrideProps<IconProps>;
    Group2582436?: PrimitiveOverrideProps<ViewProps>;
    Vector2582437?: PrimitiveOverrideProps<IconProps>;
    Group2582438?: PrimitiveOverrideProps<ViewProps>;
    Vector2582439?: PrimitiveOverrideProps<IconProps>;
    Vector2582440?: PrimitiveOverrideProps<IconProps>;
    Group2582441?: PrimitiveOverrideProps<ViewProps>;
    Vector2582442?: PrimitiveOverrideProps<IconProps>;
    Group2582443?: PrimitiveOverrideProps<ViewProps>;
    Vector2582444?: PrimitiveOverrideProps<IconProps>;
    Vector2582445?: PrimitiveOverrideProps<IconProps>;
    Group2582446?: PrimitiveOverrideProps<ViewProps>;
    Vector2582447?: PrimitiveOverrideProps<IconProps>;
    Group2582448?: PrimitiveOverrideProps<ViewProps>;
    Vector2582449?: PrimitiveOverrideProps<IconProps>;
    Vector2582450?: PrimitiveOverrideProps<IconProps>;
    Vector2582451?: PrimitiveOverrideProps<IconProps>;
    Group2582452?: PrimitiveOverrideProps<ViewProps>;
    Vector2582453?: PrimitiveOverrideProps<IconProps>;
    Vector2582454?: PrimitiveOverrideProps<IconProps>;
    Group2582455?: PrimitiveOverrideProps<ViewProps>;
    Vector2582456?: PrimitiveOverrideProps<IconProps>;
    Vector2582457?: PrimitiveOverrideProps<IconProps>;
    Vector2582458?: PrimitiveOverrideProps<IconProps>;
    Vector2582459?: PrimitiveOverrideProps<IconProps>;
    Vector2582460?: PrimitiveOverrideProps<IconProps>;
    Vector2582461?: PrimitiveOverrideProps<IconProps>;
    Vector2582462?: PrimitiveOverrideProps<IconProps>;
    Vector2582463?: PrimitiveOverrideProps<IconProps>;
    Vector2582464?: PrimitiveOverrideProps<IconProps>;
    Vector2582465?: PrimitiveOverrideProps<IconProps>;
    Group2582466?: PrimitiveOverrideProps<ViewProps>;
    Vector2582467?: PrimitiveOverrideProps<IconProps>;
    Vector2582468?: PrimitiveOverrideProps<IconProps>;
    Vector2582469?: PrimitiveOverrideProps<IconProps>;
    Vector2582470?: PrimitiveOverrideProps<IconProps>;
    Vector2582471?: PrimitiveOverrideProps<IconProps>;
    Vector2582472?: PrimitiveOverrideProps<IconProps>;
    Vector2582473?: PrimitiveOverrideProps<IconProps>;
    Vector2582474?: PrimitiveOverrideProps<IconProps>;
    Group2582475?: PrimitiveOverrideProps<ViewProps>;
    Group2582476?: PrimitiveOverrideProps<ViewProps>;
    Vector2582477?: PrimitiveOverrideProps<IconProps>;
    Vector2582478?: PrimitiveOverrideProps<IconProps>;
    Vector2582479?: PrimitiveOverrideProps<IconProps>;
    Group2582480?: PrimitiveOverrideProps<ViewProps>;
    Vector2582481?: PrimitiveOverrideProps<IconProps>;
    Vector2582482?: PrimitiveOverrideProps<IconProps>;
    Vector2582483?: PrimitiveOverrideProps<IconProps>;
    Vector2582484?: PrimitiveOverrideProps<IconProps>;
    Group2582485?: PrimitiveOverrideProps<ViewProps>;
    Group2582486?: PrimitiveOverrideProps<ViewProps>;
    Group2582487?: PrimitiveOverrideProps<ViewProps>;
    Vector2582488?: PrimitiveOverrideProps<IconProps>;
    Vector2582489?: PrimitiveOverrideProps<IconProps>;
    Vector2582490?: PrimitiveOverrideProps<IconProps>;
    Group2582491?: PrimitiveOverrideProps<ViewProps>;
    Vector2582492?: PrimitiveOverrideProps<IconProps>;
    Vector2582493?: PrimitiveOverrideProps<IconProps>;
    Group2582494?: PrimitiveOverrideProps<ViewProps>;
    Group2582495?: PrimitiveOverrideProps<ViewProps>;
    Vector2582496?: PrimitiveOverrideProps<IconProps>;
    Vector2582497?: PrimitiveOverrideProps<IconProps>;
    Vector2582498?: PrimitiveOverrideProps<IconProps>;
    Vector2582499?: PrimitiveOverrideProps<IconProps>;
    Group2582500?: PrimitiveOverrideProps<ViewProps>;
    Vector2582501?: PrimitiveOverrideProps<IconProps>;
    Group2582502?: PrimitiveOverrideProps<ViewProps>;
    Vector2582503?: PrimitiveOverrideProps<IconProps>;
    Group2582504?: PrimitiveOverrideProps<ViewProps>;
    Vector2582505?: PrimitiveOverrideProps<IconProps>;
    Vector2582506?: PrimitiveOverrideProps<IconProps>;
    Vector2582507?: PrimitiveOverrideProps<IconProps>;
    Group2582508?: PrimitiveOverrideProps<ViewProps>;
    Vector2582509?: PrimitiveOverrideProps<IconProps>;
    Vector2582510?: PrimitiveOverrideProps<IconProps>;
    Vector2582511?: PrimitiveOverrideProps<IconProps>;
    Vector2582512?: PrimitiveOverrideProps<IconProps>;
    Vector2582513?: PrimitiveOverrideProps<IconProps>;
    Group2582514?: PrimitiveOverrideProps<ViewProps>;
    Vector2582515?: PrimitiveOverrideProps<IconProps>;
    Vector2582516?: PrimitiveOverrideProps<IconProps>;
    Group2582517?: PrimitiveOverrideProps<ViewProps>;
    Vector2582518?: PrimitiveOverrideProps<IconProps>;
    Vector2582519?: PrimitiveOverrideProps<IconProps>;
    Vector2582520?: PrimitiveOverrideProps<IconProps>;
    Vector2582521?: PrimitiveOverrideProps<IconProps>;
    Vector2582522?: PrimitiveOverrideProps<IconProps>;
    Vector2582523?: PrimitiveOverrideProps<IconProps>;
    Vector2582524?: PrimitiveOverrideProps<IconProps>;
    Vector2582525?: PrimitiveOverrideProps<IconProps>;
    Vector2582526?: PrimitiveOverrideProps<IconProps>;
    Vector2582527?: PrimitiveOverrideProps<IconProps>;
    "Bottom Secondary Frame"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 51"?: PrimitiveOverrideProps<FlexProps>;
    Terms?: PrimitiveOverrideProps<TextProps>;
    Privacy?: PrimitiveOverrideProps<TextProps>;
    "CA Privacy Rights"?: PrimitiveOverrideProps<TextProps>;
    "Your Privacy Choices"?: PrimitiveOverrideProps<TextProps>;
    "\u00A9 2023 Parazon"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type FooterProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: FooterOverridesProps | undefined | null;
}>;
export default function Footer(props: FooterProps): React.ReactElement;
