/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { ViewPriceChartButtonProps } from "./ViewPriceChartButton";
import { CountryDropdownProps } from "./CountryDropdown";
import { ConnectBankButtonProps } from "./ConnectBankButton";
import { ToggleSwitchProps } from "./ToggleSwitch";
import { CheckBoxProps } from "./CheckBox";
import { BackButtonProps } from "./BackButton";
import { FinishButtonProps } from "./FinishButton";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SellStep5OverridesProps = {
    SellStep5?: PrimitiveOverrideProps<FlexProps>;
    "Frame 190"?: PrimitiveOverrideProps<FlexProps>;
    "Progress Line"?: PrimitiveOverrideProps<FlexProps>;
    "Line 76"?: PrimitiveOverrideProps<IconProps>;
    "Step 5/5"?: PrimitiveOverrideProps<TextProps>;
    "delete button"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 193"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 192"?: PrimitiveOverrideProps<FlexProps>;
    "Sell And Protect"?: PrimitiveOverrideProps<TextProps>;
    "Set your price based on Suggested Price Chart and connect your bank account to receive payments. Protect your prompt from unauthorized copying and resale for free."?: PrimitiveOverrideProps<TextProps>;
    Group44616861?: PrimitiveOverrideProps<FlexProps>;
    Vector44616862?: PrimitiveOverrideProps<IconProps>;
    Vector44616863?: PrimitiveOverrideProps<IconProps>;
    Group44616864?: PrimitiveOverrideProps<ViewProps>;
    Vector44616865?: PrimitiveOverrideProps<IconProps>;
    Vector44616866?: PrimitiveOverrideProps<IconProps>;
    Group44616867?: PrimitiveOverrideProps<ViewProps>;
    Vector44616868?: PrimitiveOverrideProps<IconProps>;
    Group44616869?: PrimitiveOverrideProps<ViewProps>;
    Vector44616870?: PrimitiveOverrideProps<IconProps>;
    Vector44616871?: PrimitiveOverrideProps<IconProps>;
    Vector44616872?: PrimitiveOverrideProps<IconProps>;
    Vector44616873?: PrimitiveOverrideProps<IconProps>;
    Vector44616874?: PrimitiveOverrideProps<IconProps>;
    Vector44616875?: PrimitiveOverrideProps<IconProps>;
    Vector44616876?: PrimitiveOverrideProps<IconProps>;
    Vector44616877?: PrimitiveOverrideProps<IconProps>;
    Vector44616878?: PrimitiveOverrideProps<IconProps>;
    Vector44616879?: PrimitiveOverrideProps<IconProps>;
    Vector44616880?: PrimitiveOverrideProps<IconProps>;
    Group44616881?: PrimitiveOverrideProps<ViewProps>;
    Vector44616882?: PrimitiveOverrideProps<IconProps>;
    Vector44616883?: PrimitiveOverrideProps<IconProps>;
    Group44616884?: PrimitiveOverrideProps<ViewProps>;
    Vector44616885?: PrimitiveOverrideProps<IconProps>;
    file44616886?: PrimitiveOverrideProps<ViewProps>;
    Vector44616887?: PrimitiveOverrideProps<IconProps>;
    Vector44616888?: PrimitiveOverrideProps<IconProps>;
    Group44616889?: PrimitiveOverrideProps<ViewProps>;
    Vector44616890?: PrimitiveOverrideProps<IconProps>;
    Vector44616891?: PrimitiveOverrideProps<IconProps>;
    Group44616892?: PrimitiveOverrideProps<ViewProps>;
    Vector44616893?: PrimitiveOverrideProps<IconProps>;
    Vector44616894?: PrimitiveOverrideProps<IconProps>;
    Group44616895?: PrimitiveOverrideProps<ViewProps>;
    Vector44616896?: PrimitiveOverrideProps<IconProps>;
    Vector44616897?: PrimitiveOverrideProps<IconProps>;
    Group44616898?: PrimitiveOverrideProps<ViewProps>;
    Vector44616899?: PrimitiveOverrideProps<IconProps>;
    Vector44616900?: PrimitiveOverrideProps<IconProps>;
    Group44616901?: PrimitiveOverrideProps<ViewProps>;
    Vector44616902?: PrimitiveOverrideProps<IconProps>;
    Vector44616903?: PrimitiveOverrideProps<IconProps>;
    Group44616904?: PrimitiveOverrideProps<ViewProps>;
    Vector44616905?: PrimitiveOverrideProps<IconProps>;
    Vector44616906?: PrimitiveOverrideProps<IconProps>;
    Vector44616907?: PrimitiveOverrideProps<IconProps>;
    file44616908?: PrimitiveOverrideProps<ViewProps>;
    Vector44616909?: PrimitiveOverrideProps<IconProps>;
    Vector44616910?: PrimitiveOverrideProps<IconProps>;
    Group44616911?: PrimitiveOverrideProps<ViewProps>;
    Vector44616912?: PrimitiveOverrideProps<IconProps>;
    Vector44616913?: PrimitiveOverrideProps<IconProps>;
    Group44616914?: PrimitiveOverrideProps<ViewProps>;
    Vector44616915?: PrimitiveOverrideProps<IconProps>;
    Vector44616916?: PrimitiveOverrideProps<IconProps>;
    Group44616917?: PrimitiveOverrideProps<ViewProps>;
    Vector44616918?: PrimitiveOverrideProps<IconProps>;
    Vector44616919?: PrimitiveOverrideProps<IconProps>;
    Group44616920?: PrimitiveOverrideProps<ViewProps>;
    Vector44616921?: PrimitiveOverrideProps<IconProps>;
    Vector44616922?: PrimitiveOverrideProps<IconProps>;
    Group44616923?: PrimitiveOverrideProps<ViewProps>;
    Vector44616924?: PrimitiveOverrideProps<IconProps>;
    Vector44616925?: PrimitiveOverrideProps<IconProps>;
    Group44616926?: PrimitiveOverrideProps<ViewProps>;
    Vector44616927?: PrimitiveOverrideProps<IconProps>;
    Vector44616928?: PrimitiveOverrideProps<IconProps>;
    Vector44616929?: PrimitiveOverrideProps<IconProps>;
    Vector44616930?: PrimitiveOverrideProps<IconProps>;
    Group44616931?: PrimitiveOverrideProps<ViewProps>;
    Vector44616932?: PrimitiveOverrideProps<IconProps>;
    Vector44616933?: PrimitiveOverrideProps<IconProps>;
    Group44616934?: PrimitiveOverrideProps<ViewProps>;
    Vector44616935?: PrimitiveOverrideProps<IconProps>;
    Vector44616936?: PrimitiveOverrideProps<IconProps>;
    Vector44616937?: PrimitiveOverrideProps<IconProps>;
    Vector44616938?: PrimitiveOverrideProps<IconProps>;
    Group44616939?: PrimitiveOverrideProps<ViewProps>;
    Vector44616940?: PrimitiveOverrideProps<IconProps>;
    Vector44616941?: PrimitiveOverrideProps<IconProps>;
    Vector44616942?: PrimitiveOverrideProps<IconProps>;
    Vector44616943?: PrimitiveOverrideProps<IconProps>;
    Vector44616944?: PrimitiveOverrideProps<IconProps>;
    Vector44616945?: PrimitiveOverrideProps<IconProps>;
    Vector44616946?: PrimitiveOverrideProps<IconProps>;
    Vector44616947?: PrimitiveOverrideProps<IconProps>;
    Vector44616948?: PrimitiveOverrideProps<IconProps>;
    Vector44616949?: PrimitiveOverrideProps<IconProps>;
    Vector44616950?: PrimitiveOverrideProps<IconProps>;
    Group44616951?: PrimitiveOverrideProps<ViewProps>;
    Group44616952?: PrimitiveOverrideProps<ViewProps>;
    Vector44616953?: PrimitiveOverrideProps<IconProps>;
    Vector44616954?: PrimitiveOverrideProps<IconProps>;
    lock?: PrimitiveOverrideProps<ViewProps>;
    Group44616956?: PrimitiveOverrideProps<ViewProps>;
    Vector44616957?: PrimitiveOverrideProps<IconProps>;
    Vector44616958?: PrimitiveOverrideProps<IconProps>;
    Vector44616959?: PrimitiveOverrideProps<IconProps>;
    Vector44616960?: PrimitiveOverrideProps<IconProps>;
    Group44616961?: PrimitiveOverrideProps<ViewProps>;
    Vector44616962?: PrimitiveOverrideProps<IconProps>;
    Vector44616963?: PrimitiveOverrideProps<IconProps>;
    Group44616964?: PrimitiveOverrideProps<ViewProps>;
    gra6_b44616965?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616966?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616967?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616968?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616969?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616970?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616971?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616972?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616973?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616974?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616975?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616976?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616977?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616978?: PrimitiveOverrideProps<IconProps>;
    gra6_b44616979?: PrimitiveOverrideProps<IconProps>;
    Vector44616980?: PrimitiveOverrideProps<IconProps>;
    "Frame 216"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 19744616982"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 19744616983"?: PrimitiveOverrideProps<FlexProps>;
    Price?: PrimitiveOverrideProps<TextProps>;
    "Please refer to the Suggested Price Chart before setting your price. Ensure your price falls within the price limits."?: PrimitiveOverrideProps<TextProps>;
    "Frame 215"?: PrimitiveOverrideProps<FlexProps>;
    "View Price Chart Button"?: ViewPriceChartButtonProps;
    "Frame 173"?: PrimitiveOverrideProps<FlexProps>;
    "List Title"?: PrimitiveOverrideProps<TextProps>;
    "Line 80"?: PrimitiveOverrideProps<IconProps>;
    "Frame 219"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 21844616992"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 21744616993"?: PrimitiveOverrideProps<FlexProps>;
    Payment?: PrimitiveOverrideProps<TextProps>;
    "Connect your Bank Account with Stripe, keep 80% of revenue from every sale of your prompt."?: PrimitiveOverrideProps<TextProps>;
    "Frame 19544616996"?: PrimitiveOverrideProps<FlexProps>;
    "Country of Residence"?: PrimitiveOverrideProps<TextProps>;
    "We need to know this for sending payouts. Please read our FAQ if your country does not appear here."?: PrimitiveOverrideProps<TextProps>;
    "Country Dropdown"?: CountryDropdownProps;
    "Connect Bank Button"?: ConnectBankButtonProps;
    "Line 81"?: PrimitiveOverrideProps<IconProps>;
    "Frame 21844617002"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 21744617003"?: PrimitiveOverrideProps<FlexProps>;
    "Protection and Acknowledgement"?: PrimitiveOverrideProps<TextProps>;
    "Frame 19544617005"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 220"?: PrimitiveOverrideProps<FlexProps>;
    "Add Prompt Protection (Recommended)"?: PrimitiveOverrideProps<TextProps>;
    "Toggle Switch"?: ToggleSwitchProps;
    "Enable free protection for your prompt to prevent unauthorized copying and resale. Automatically activated once your prompt is published."?: PrimitiveOverrideProps<TextProps>;
    "Frame 21844617010"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 221"?: PrimitiveOverrideProps<FlexProps>;
    "Terms and Conditions"?: PrimitiveOverrideProps<TextProps>;
    "By clicking \u201CI Agree\u201D, you acknowledge and accept our terms and conditions."?: PrimitiveOverrideProps<TextProps>;
    CheckBox?: CheckBoxProps;
    "Frame 199"?: PrimitiveOverrideProps<FlexProps>;
    "Back Button"?: BackButtonProps;
    "Line 77"?: PrimitiveOverrideProps<IconProps>;
    "Finish Button"?: FinishButtonProps;
} & EscapeHatchProps;
export declare type SellStep5Props = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: SellStep5OverridesProps | undefined | null;
}>;
export default function SellStep5(props: SellStep5Props): React.ReactElement;
